// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CentroLote", b =>
                {
                    b.Property<int>("CentrosId")
                        .HasColumnType("integer");

                    b.Property<int>("LotesId")
                        .HasColumnType("integer");

                    b.HasKey("CentrosId", "LotesId");

                    b.HasIndex("LotesId");

                    b.ToTable("Centro_Lote", (string)null);
                });

            modelBuilder.Entity("VestaApi.Models.Ayuntamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreMunicipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ayuntamientos");
                });

            modelBuilder.Entity("VestaApi.Models.Centro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdAyuntamiento")
                        .HasColumnType("integer");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdAyuntamiento");

                    b.ToTable("Centros");
                });

            modelBuilder.Entity("VestaApi.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailContacto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoAprobacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("VestaApi.Models.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gravedad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("LoteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("VestaApi.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdAyuntamiento")
                        .HasColumnType("integer");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdAyuntamiento");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("VestaApi.Models.Nomina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutaArchivoPDF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Nominas");
                });

            modelBuilder.Entity("VestaApi.Models.Pliego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdLote")
                        .HasColumnType("integer");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutaURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdLote");

                    b.ToTable("Pliegos");
                });

            modelBuilder.Entity("VestaApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("boolean");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IdAyuntamiento")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenVerificacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdAyuntamiento");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VestaApi.Models.UsuarioEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurriculumURl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoSolicitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioEmpresas");
                });

            modelBuilder.Entity("CentroLote", b =>
                {
                    b.HasOne("VestaApi.Models.Centro", null)
                        .WithMany()
                        .HasForeignKey("CentrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VestaApi.Models.Lote", null)
                        .WithMany()
                        .HasForeignKey("LotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VestaApi.Models.Centro", b =>
                {
                    b.HasOne("VestaApi.Models.Ayuntamiento", "Ayuntamiento")
                        .WithMany("Centros")
                        .HasForeignKey("IdAyuntamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ayuntamiento");
                });

            modelBuilder.Entity("VestaApi.Models.Incidencia", b =>
                {
                    b.HasOne("VestaApi.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("VestaApi.Models.Lote", "LoteAfectado")
                        .WithMany()
                        .HasForeignKey("LoteId");

                    b.HasOne("VestaApi.Models.Usuario", "Autor")
                        .WithMany("IncidenciasReportadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Empresa");

                    b.Navigation("LoteAfectado");
                });

            modelBuilder.Entity("VestaApi.Models.Lote", b =>
                {
                    b.HasOne("VestaApi.Models.Ayuntamiento", "Ayuntamiento")
                        .WithMany("LotesOfertados")
                        .HasForeignKey("IdAyuntamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VestaApi.Models.Empresa", "Empresa")
                        .WithMany("LotesAsignados")
                        .HasForeignKey("IdEmpresa");

                    b.Navigation("Ayuntamiento");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("VestaApi.Models.Nomina", b =>
                {
                    b.HasOne("VestaApi.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VestaApi.Models.Usuario", "Usuario")
                        .WithMany("MisNominas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VestaApi.Models.Pliego", b =>
                {
                    b.HasOne("VestaApi.Models.Lote", "Lote")
                        .WithMany("Pliegos")
                        .HasForeignKey("IdLote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("VestaApi.Models.Usuario", b =>
                {
                    b.HasOne("VestaApi.Models.Ayuntamiento", "Ayuntamiento")
                        .WithMany("UsuariosGestores")
                        .HasForeignKey("IdAyuntamiento");

                    b.Navigation("Ayuntamiento");
                });

            modelBuilder.Entity("VestaApi.Models.UsuarioEmpresa", b =>
                {
                    b.HasOne("VestaApi.Models.Empresa", "Empresa")
                        .WithMany("Relaciones")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VestaApi.Models.Usuario", "Usuario")
                        .WithMany("Vinculaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VestaApi.Models.Ayuntamiento", b =>
                {
                    b.Navigation("Centros");

                    b.Navigation("LotesOfertados");

                    b.Navigation("UsuariosGestores");
                });

            modelBuilder.Entity("VestaApi.Models.Empresa", b =>
                {
                    b.Navigation("LotesAsignados");

                    b.Navigation("Relaciones");
                });

            modelBuilder.Entity("VestaApi.Models.Lote", b =>
                {
                    b.Navigation("Pliegos");
                });

            modelBuilder.Entity("VestaApi.Models.Usuario", b =>
                {
                    b.Navigation("IncidenciasReportadas");

                    b.Navigation("MisNominas");

                    b.Navigation("Vinculaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
